controllers_base:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    exclude: ../src/Controller/Api/ # Exclut le dossier API de ce scan



# Importe les routes définies dans api.yaml
api_routes:
    resource: 'api.yaml'
