security:
    password_hashers:
        App\Entity\Utilisateur: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login_check
            stateless: true

            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main: 
            stateless: true
            provider: app_user_provider 
            jwt: ~ 

            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
        
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        # - { path: ^/api/admin, roles: ROLE_ADMIN } # Décommente si besoin
        # - { path: ^/api/employe, roles: [ROLE_EMPLOYEE, ROLE_ADMIN] } # Décommente si besoin
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY } # Protéger le reste de /api



when@test:
    security:
        password_hashers:
            App\Entity\Utilisateur:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
