# Routes JWT
api_login_check:
    path: /api/login_check
    methods: ['POST']

api_token_refresh:
    path: /api/token/refresh
    methods: ['POST']

# Routes Covoiturage
api_covoiturages:
    path: /api/covoiturages
    methods: ['GET']
    controller: App\Controller\Api\CovoiturageController::list

api_covoiturage_show:
    path: /api/covoiturages/{id}
    methods: ['GET']
    controller: App\Controller\Api\CovoiturageController::show

api_covoiturage_create:
    path: /api/covoiturages/new
    methods: ['POST']
    controller: App\Controller\Api\CovoiturageController::create

api_covoiturage_update:
    path: /api/covoiturages/{id}
    methods: ['PUT']
    controller: App\Controller\Api\CovoiturageController::update

api_covoiturage_delete:
    path: /api/covoiturages/{id}
    methods: ['DELETE']
    controller: App\Controller\Api\CovoiturageController::delete

api_covoiturage_reserver:
    path: /api/covoiturages/{id}/reserver
    methods: ['POST']
    controller: App\Controller\Api\CovoiturageController::reserver

api_covoiturage_annuler:
    path: /api/covoiturages/{id}/annuler-reservation
    methods: ['DELETE']
    controller: App\Controller\Api\CovoiturageController::annulerReservation
